sudo: false
language: node_js
node_js:
  - "7"
script:
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $PUSH_TOKEN
  on:
    branch: master
